#include "fumesensor.h"

void FUMESENSOR_init(void)
{
    GPIO_Init(FUMESENSOR_PORT,FUMESENSOR_PIN,PIN_INPUT,1);
    GPIO_Init(FUMESENSOR_PORT_DIGITAL,FUMESENSOR_PIN_DIGITAL,PIN_INPUT,1);
}

uint8 FUMESENSOR_read(void)
{
    return GPIO_ReadPin(FUMESENSOR_PORT_DIGITAL,FUMESENSOR_PIN_DIGITAL);
}

uint8 FUMESENSOR_readAdc(void)
{
    return GPIO_ReadPin(FUMESENSOR_PORT,FUMESENSOR_PIN);
}